# Generated by Django 3.1.4 on 2020-12-10 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_olympic_history', '0005_athleteevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('noc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_olympic_history.noc')),
            ],
        ),
        migrations.AddField(
            model_name='noc',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_olympic_history.region'),
        ),
        migrations.AddField(
            model_name='athleteevent',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_olympic_history.team'),
            preserve_default=False,
        ),
    ]
