# Generated by Django 3.1.4 on 2020-12-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_olympic_history', '0008_auto_20201210_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
