# Generated by Django 3.1.4 on 2020-12-10 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_olympic_history', '0009_auto_20201210_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noc',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_olympic_history.region'),
        ),
    ]
