# Generated by Django 3.1.4 on 2020-12-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_olympic_history', '0011_auto_20201210_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal',
            name='type',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
