# Generated by Django 3.1.4 on 2020-12-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_olympic_history', '0012_auto_20201210_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteevent',
            name='athlete_age',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='athleteevent',
            name='athlete_height',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='athleteevent',
            name='athlete_weight',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
